title: OmniCanva
description: Free & Premium Templates for Students & Creators

url: "https://himanshutyagiji.github.io"
baseurl: "/OmniCanva"

author: TyagiMultiTech
email: your@email.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:categories/:title/

# Plugins (GitHub supported only)
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Collections
collections:
  templates:
    output: true
    permalink: /template/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "templates"
    values:
      layout: "template"

# Exclude unnecessary files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

# Disable theme (important)
theme: null

# Google Sheets Config (IMPORTANT 🔥)
google_sheet_id: "PASTE_YOUR_SHEET_ID"
google_script_url: "PASTE_YOUR_APPS_SCRIPT_URL"
